/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    quaranteDeux
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_quaranteDeux
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    fact
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Main_fact
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
